version: "3"

services:
  ner:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: python3 /app/src/app.py
    ports:
      - "8091:8080"
    environment:
      - DATA_FOLDER_PATH=${DATA_FOLDER_PATH}
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - ./data:${DATA_FOLDER_PATH}
